Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "EEE" -RegistryValue "0"
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "FlowControl" -RegistryValue "0"
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "IPChecksumOffloadIPv4" -RegistryValue "3"
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "InterruptModeration" -RegistryValue "0"
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "ModernStandbyWoLMagicPacket" -RegistryValue "0"
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "LsoV2IPv4" -RegistryValue "1"
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "LsoV2IPv6" -RegistryValue "1"
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "NumRssQueues" -RegistryValue "2"
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "PMARPOffload" -RegistryValue "1"
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "PMNSOffload" -RegistryValue "1"
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "PriorityVLANTag" -RegistryValue "1"
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "RSS" -RegistryValue "1"
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "WakeOnMagicPacket" -RegistryValue "0"
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "WakeOnPattern" -RegistryValue "0"
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "ReceiveBuffers" -RegistryValue "2048"
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "TransmitBuffers" -RegistryValue "2048"
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "TCPChecksumOffloadIPv4" -RegistryValue "3"
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "TCPChecksumOffloadIPv6" -RegistryValue "3"
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "UDPChecksumOffloadIPv4" -RegistryValue "3"
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "UDPChecksumOffloadIPv6" -RegistryValue "3"
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "DMACoalescing" -RegistryValue "0"
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "EEELinkAdvertisement" -RegistryValue "0"
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "EnablePME" -RegistryValue "0"
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "ITR" -RegistryValue "0"
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "ReduceSpeedOnPowerDown" -RegistryValue "0"
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "WaitAutoNegComplete" -RegistryValue "0"
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "WakeOnLink" -RegistryValue "0"
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "AdvancedEEE" -RegistryValue "0"
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "EnableGreenEthernet" -RegistryValue "0"
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "GigaLite" -RegistryValue "0"
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "PowerSavingMode" -RegistryValue "0"
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "S5WakeOnLan" -RegistryValue "0"
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "WolShutdownLinkSpeed" -RegistryValue "2"
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "LogLinkStateEvent" -RegistryValue "16"
Set-NetAdapterAdvancedProperty -Name "" -RegistryKeyword "WakeOnMagicPacketFromS5" -RegistryValue "0"
Set-NetAdapterAdvancedProperty -Name "" -DisplayName "Ultra Low Power Mode" -DisplayValue "Disabled"
Set-NetAdapterAdvancedProperty -Name "" -DisplayName "System Idle Power Saver" -DisplayValue "Disabled"
Set-NetAdapterAdvancedProperty -Name "" -DisplayName "Selective Suspend" -DisplayValue "Disabled"
Set-NetAdapterAdvancedProperty -Name "" -DisplayName "Selective Suspend Idle Timeout" -DisplayValue "60"
Set-NetAdapterAdvancedProperty -Name "" -DisplayName "Link Speed Battery Saver" -DisplayValue "Disabled"